
language: cpp

compiler:
  - clang
  - gcc

os:
  - linux

env:
  global:
    - MAKEJOBS=-j3
    - RUN_TESTS=true
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
    - GOAL=all

cache:
  apt: true
  directories:
  - $HOME/.ccache

addons:
  apt:
    packages:
      - libelf-dev
      - libssl-dev

before_script:
  - wget http://gtf.org/garzik/bitcoin/moxiebox-root-20150918.tar.gz
  - tar -xzvf moxiebox-root-20150918.tar.gz

script:
  - export PATH=$PATH:`pwd`/local/root/usr/bin
  - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
  - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
  - MOXIEBOX_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export CCACHE_READONLY=1; fi
  - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
  - ./configure --cache-file=config.cache $MOXIEBOX_CONFIG_ALL $MOXIEBOX_CONFIG || ( cat config.log && false)
  - make -s $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL ; false )
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
  - if [ "$RUN_TESTS" = "true" ]; then make distcheck; fi

